"""empty message

Revision ID: 00e7e8763cf9
Revises: 2c3ac5559ded
Create Date: 2025-07-22 16:39:28.055471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e7e8763cf9'
down_revision = '2c3ac5559ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_bulk', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('parent_transaction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transaction_parent_transaction_id', 'transaction', ['parent_transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_transaction_id')
        batch_op.drop_column('is_bulk')

    # ### end Alembic commands ###
