"""Change float to numeric for financial fields

Revision ID: 0cac374427c4
Revises: 4e0acd24a1be
Create Date: 2025-09-03 13:57:17.219608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cac374427c4'
down_revision = '4e0acd24a1be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
