"""empty message

Revision ID: 2c3ac5559ded
Revises: 1b5288305d43
Create Date: 2025-07-22 15:55:17.441635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3ac5559ded'
down_revision = '1b5288305d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
