"""Initial migration from consolidated models

Revision ID: 300e2f6324ea
Revises: 
Create Date: 2025-09-03 16:37:21.511220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300e2f6324ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord_reference', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'landlord', ['landlord_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord_reference', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
