""""Add_utility_split_to_Property"

Revision ID: 338c2d53fcf1
Revises: e9aaf9a24160
Create Date: 2025-08-14 14:13:30.015413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338c2d53fcf1'
down_revision = 'e9aaf9a24160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('landlord_reference_code_key'), type_='unique')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('landlord_portion', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('utility_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'account', ['utility_account_id'], ['id'])

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tenant_reference_code_key'), type_='unique')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('tenant_reference_code_key'), ['reference_code'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('utility_account_id')
        batch_op.drop_column('landlord_portion')

    with op.batch_alter_table('landlord', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('landlord_reference_code_key'), ['reference_code'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
