""""Add_utility_split_to_Property"

Revision ID: 338c2d53fcf1
Revises: e9aaf9a24160
Create Date: 2025-08-14 14:13:30.015413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338c2d53fcf1'
down_revision = 'e9aaf9a24160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('landlord_portion', sa.Float(), nullable=True))
        # batch_op.add_column(sa.Column('utility_account_id', sa.Integer(), nullable=True))
        # batch_op.create_foreign_key('fk_property_utility_account_id_account', 'account', ['utility_account_id'], ['id'])
        pass

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        # batch_op.create_foreign_key('fk_user_roles_role_id_role', 'role', ['role_id'], ['id'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_roles_role_id_role', type_='foreignkey')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_constraint('fk_property_utility_account_id_account', type_='foreignkey')
        batch_op.drop_column('utility_account_id')
        batch_op.drop_column('landlord_portion')

    # ### end Alembic commands ###
