"""empty message

Revision ID: 3838d9fbae4c
Revises: 572234588cda
Create Date: 2025-07-22 15:44:09.044962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3838d9fbae4c'
down_revision = '572234588cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('reviewed', sa.Boolean(), nullable=False))
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('reviewed')

    # ### end Alembic commands ###
