"""Change float to numeric for financial fields

Revision ID: 3f03b38767e5
Revises: 52d4c2febcfc
Create Date: 2025-09-03 13:58:55.276608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f03b38767e5'
down_revision = '52d4c2febcfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('reference')

    with op.batch_alter_table('landlord_reference', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'landlord', ['landlord_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord_reference', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.VARCHAR(length=128), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
