"""Add landlord reference model

Revision ID: 4e0acd24a1be
Revises: 7e44d782114f
Create Date: 2025-09-03 13:33:28.936946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0acd24a1be'
down_revision = '7e44d782114f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landlord_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_code', sa.String(length=64), nullable=True),
    sa.Column('landlord_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlord.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('landlord_reference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_landlord_reference_reference_code'), ['reference_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord_reference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_landlord_reference_reference_code'))

    op.drop_table('landlord_reference')
    # ### end Alembic commands ###