"""empty message

Revision ID: 525b019eafee
Revises: dde3c4790b20
Create Date: 2025-07-28 15:47:23.131673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525b019eafee'
down_revision = 'dde3c4790b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'property', ['property_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('property_id')

    # ### end Alembic commands ###
