"""Change float to numeric for financial fields

Revision ID: 52d4c2febcfc
Revises: 0cac374427c4
Create Date: 2025-09-03 13:58:16.494909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d4c2febcfc'
down_revision = '0cac374427c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
