"""Add town and postcode to property address

Revision ID: 6146c7ab5c94
Revises: fbc21fdb16a5
Create Date: 2025-09-03 12:05:20.862896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6146c7ab5c94'
down_revision = 'fbc21fdb16a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
