"""Add town and postcode to landlord address

Revision ID: 7e44d782114f
Revises: 6146c7ab5c94
Create Date: 2025-09-03 12:15:23.652133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e44d782114f'
down_revision = '6146c7ab5c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
