"""Add town and postcode to landlord address

Revision ID: 7e44d782114f
Revises: 6146c7ab5c94
Create Date: 2025-09-03 12:15:23.652133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e44d782114f'
down_revision = '6146c7ab5c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_line_1', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('town', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('postcode', sa.String(length=20), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.drop_column('postcode')
        batch_op.drop_column('town')
        batch_op.drop_column('address_line_1')

    # ### end Alembic commands ###
