"""Add end_date and is_archived to Tenant

Revision ID: cc4bde747cb4
Revises: 3f03b38767e5
Create Date: 2025-09-03 14:27:54.093101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4bde747cb4'
down_revision = '3f03b38767e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('is_archived')
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###
