"""empty message

Revision ID: dde3c4790b20
Revises: 00e7e8763cf9
Create Date: 2025-07-25 10:27:31.634923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde3c4790b20'
down_revision = '00e7e8763cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_transaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.Column('reference_code', sa.VARCHAR(length=128), nullable=True),
    sa.Column('status', sa.VARCHAR(length=64), nullable=True),
    sa.Column('category', sa.VARCHAR(length=64), nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), nullable=True),
    sa.Column('landlord_id', sa.INTEGER(), nullable=True),
    sa.Column('account_id', sa.INTEGER(), nullable=True),
    sa.Column('rent_charge_batch_id', sa.INTEGER(), nullable=True),
    sa.Column('processed', sa.BOOLEAN(), nullable=False),
    sa.Column('reviewed', sa.BOOLEAN(), nullable=False),
    sa.Column('is_bulk', sa.BOOLEAN(), nullable=False),
    sa.Column('parent_transaction_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlord.id'], ),
    sa.ForeignKeyConstraint(['parent_transaction_id'], ['transaction.id'], name=op.f('fk_transaction_parent_transaction_id')),
    sa.ForeignKeyConstraint(['rent_charge_batch_id'], ['rent_charge_batch.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
