""""AddCompanyModel"

Revision ID: e0bab2b88d6e
Revises: 144d6c011aa2
Create Date: 2025-07-22 09:33:34.724190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0bab2b88d6e'
down_revision = '144d6c011aa2'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('company',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=128), nullable=True),
    # sa.Column('address', sa.String(length=256), nullable=True),
    # sa.Column('logo', sa.String(length=256), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    # ### end Alembic commands ###
