"""Add reference to Expense

Revision ID: fbc21fdb16a5
Revises: 338c2d53fcf1
Create Date: 2025-08-27 13:22:25.180964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc21fdb16a5'
down_revision = '338c2d53fcf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('reference')

    # ### end Alembic commands ###
