"""empty message

Revision ID: 1b5288305d43
Revises: 3838d9fbae4c
Create Date: 2025-07-22 15:50:21.749891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5288305d43'
down_revision = '3838d9fbae4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('bank_account_number', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('bank_sort_code', sa.String(length=10), nullable=True))

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('landlord', schema=None) as batch_op:
        batch_op.drop_column('bank_sort_code')
        batch_op.drop_column('bank_account_number')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('address')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
