"""empty message

Revision ID: 4791a8c12e1d
Revises: 49c27b664aba
Create Date: 2025-07-15 12:23:02.355541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4791a8c12e1d'
down_revision = '49c27b664aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receives_email_statements', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord', schema=None) as batch_op:
        batch_op.drop_column('receives_email_statements')

    # ### end Alembic commands ###
