"""empty message

Revision ID: 572234588cda
Revises: e0bab2b88d6e
Create Date: 2025-07-22 15:43:10.193145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572234588cda'
down_revision = 'e0bab2b88d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_landlord_reference_code'), ['reference_code'], unique=True)

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_reference_code'), ['reference_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_reference_code'))

    with op.batch_alter_table('landlord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_landlord_reference_code'))

    # ### end Alembic commands ###
